sm_data/urls.py
from django.urls import path
from . import views

app_name = 'data'

urlpatterns = [
    path('regist/', views.regist_data, name='regist'),
]

sm_survay/urls.py
from django.urls import path
from . import views

app_name = 'survay'

urlpatterns = [
    path('index/', views.index_template, name='index'),
    path('create/', views.create_template, name='create'),
    path('history/', views.history_template, name='history'),
    path('detail/<int:pk>', views.detail_template, name='detail'),
    path('edit/<int:pk>', views.edit_template, name='edit'),
    path('delete/<int:pk>', views.delete_survay, name='delete'),
    path('delete/cluster_log/<int:pk>', views.delete_cluster_log, name='delete_cluster_log'),
    path('download/<int:pk>', views.download, name='download'),
]

survay_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('auth/', include('authuser.urls')),
    path('api/data/', include('sm_data.urls')),
    path('mng/dashboard/', include('sm_dashboard.urls')),
    path('mng/survay/', include('sm_survay.urls')),
]

sm_survay/models.py
from django.db             import models
from soft_delete_it.models import SoftDeleteModel

class SurvayConstants(object):
    TYPE_CHOICES = (
        (1, 'YES or NO'),
        (2, 'Level'),
    )
    UPDATE_STATUS_CHOICES = (
        (1, 'Under_Review'),
        (2, 'Completed'),
        (3, 'Reject'),
    )
    UPDATE_TYPE_CHOICES = (
        (1, 'Survay'),
        (2, 'Cluster'),
    )

    @classmethod
    def get_type_index(cls, value):
        inverse = {v:k for k, v in dict(cls.TYPE_CHOICES).items()}
        return inverse[value]

    @classmethod
    def get_update_status_index(cls, value):
        inverse = {v:k for k, v in dict(cls.UPDATE_STATUS_CHOICES).items()}
        return inverse[value]


class Cluster(SoftDeleteModel):
    class Meta:
        verbose_name = 'クラスタ'
        db_table     = 'clusters'

    number     = models.SmallIntegerField(default=0, verbose_name='番号')
    text       = models.CharField(max_length=500, null=False, verbose_name="質問内容")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")

    def __str__(self):
        return self.text


class Question(models.Model):
    class Meta:
        verbose_name = '質問'
        db_table     = 'questions'
        # indexes      = [
        #     models.Index(fields=['id'])]

    number     = models.SmallIntegerField(default=0, verbose_name='番号')
    text       = models.CharField(max_length=255, null=False, verbose_name="質問内容")
    type       = models.SmallIntegerField(default=0, verbose_name='タイプ', choices=SurvayConstants.TYPE_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")

    def __str__(self):
        return self.text


class Category(models.Model):
    class Meta:
        verbose_name = 'カテゴリ'
        db_table     = 'category'
        # indexes      = [
        #     models.Index(fields=['id'])]

    number     = models.SmallIntegerField(default=0, verbose_name='番号')
    text       = models.CharField(max_length=255, null=False, verbose_name="カテゴリ内容")
    page       = models.SmallIntegerField(default=0, verbose_name='ページ')
    questions  = models.ManyToManyField(Question)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")

    def __str__(self):
        return self.text


class Version(models.Model):
    class Meta:
        verbose_name = 'バージョン'
        db_table     = 'versions'
        # indexes      = [
        #     models.Index(fields=['id'])]

    number     = models.SmallIntegerField(default=1, verbose_name='バージョン')
    categories = models.ManyToManyField(Category)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")

    def __str__(self):
        return self.number


class Survay(SoftDeleteModel):
    class Meta:
        verbose_name = 'アンケート'
        db_table     = 'survays'
        # indexes      = [
        #     models.Index(fields=['id'])]

    title      = models.CharField(max_length=255, null=False, verbose_name="アンケート名")
    path       = models.CharField(max_length=255, default='', verbose_name="ファイルパス")
    versions   = models.ManyToManyField(Version)
    clusters   = models.ManyToManyField(Cluster)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")

    def __str__(self):
        return self.title


class ClusterUpdateLog(SoftDeleteModel):
    class Meta:
        verbose_name = 'クラスタ更新ログ'
        db_table     = 'cluster_update_logs'
        # indexes      = [
        #     models.Index(fields=['id'])]

    cluster        = models.ForeignKey(Cluster, on_delete=models.DO_NOTHING)
    text           = models.CharField(max_length=500, default='', verbose_name="変更後文章")
    status         = models.SmallIntegerField(default=0, verbose_name='申請ステータス', choices=SurvayConstants.UPDATE_STATUS_CHOICES)
    update_comment = models.CharField(max_length=500, default='', verbose_name="更新コメント")
    reject_comment = models.CharField(max_length=500, default='', verbose_name="却下理由")
    created_at     = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    updated_at     = models.DateTimeField(auto_now=True, verbose_name="更新日時")

sm_survay/views.py
import os,openpyxl,hashlib
import urllib.parse
from django.http import Http404, JsonResponse
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from .models import (
    Survay,
    Version,
    Category,
    Question,
    Cluster,
    ClusterUpdateLog,
    SurvayConstants,
)

@login_required
def index_template(request):
    survays = Survay.objects.all()
    context = {
        'survays' : survays
    }
    return render(request, 'survay/index.html', context)

@login_required
def detail_template(request, pk):
    survay = get_object_or_404(Survay, pk=pk)
    context = {
        'survay' : survay
    }
    return render(request, 'survay/detail.html', context)

@login_required
def create_template(request):
    if request.method != 'POST':
        return render(request, 'survay/create.html')
    else:
        file  = request.FILES['survay_file']
        title = request.POST['title']
        path  = __create_temp_file(file)
        survay, clusters = __parse_xlsx_file(path)
        __regist_servay(title, path, survay, clusters)
        request.session['alert_info'] = {
            'text' : '新規レコードの登録が完了しました。',
            'type' : 'success'
        }
        return redirect('survay:index')

@login_required
def edit_template(request, pk):
    survay = get_object_or_404(Survay, pk=pk)
    if request.method != 'POST':
        return Http404
    else:
        current = None
        for c in survay.clusters.all():
            if c.number == int(request.POST['number']):
                current = c
                break
        log = ClusterUpdateLog()
        log.cluster_id = current.id
        log.update_comment = request.POST['comment']
        log.text    = request.POST['text']
        log.status  = SurvayConstants.get_update_status_index('Under_Review')
        log.save()

        return JsonResponse({'result' : 'ok'})


@login_required
def delete_survay(request, pk):
    survay = get_object_or_404(Survay, pk=pk)
    if request.method != 'POST':
        survay.delete()
        request.session['alert_info'] = {
            'text' : '対象レコードを削除しました。',
            'type' : 'success'
        }
        return redirect('survay:index')
    raise Http404

@login_required
def history_template(request):
    if request.method != 'POST':
        context = {
            'logs' : ClusterUpdateLog.objects.all()
        }
        return render(request, 'survay/history.html', context)
    raise Http404

@login_required
def delete_cluster_log(request, pk):
    log = get_object_or_404(ClusterUpdateLog, pk=pk)
    log.delete()
    request.session['alert_info'] = {
        'text' : '対象の申請を取り下げました。',
        'type' : 'success'
    }
    return redirect('survay:history')

@login_required
def download(request, pk):
    survay = get_object_or_404(Survay, pk=pk)
    if request.method != 'POST' and os.path.exists(survay.path):
        with open(survay.path, 'rb') as fh:
            file_name = '{}.{}'.format(survay.title, survay.path.split('.')[-1])
            response  = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename={}'.format(urllib.parse.quote(file_name))
            return response
    raise Http404

def __create_temp_file(file):
    file_name = '{}.{}'.format(hashlib.md5(file.name.encode('utf-8')).hexdigest(), file.name.split('.')[-1])
    file_path = os.path.join(os.path.dirname(__file__), 'temp', file_name)
    with open(file_path, 'wb') as f:
        for chunk in file.chunks():
            f.write(chunk)
    return file_path

def __parse_xlsx_file(path):
    wb    = openpyxl.load_workbook(path)
    sheet = wb['survay']
    survay  = {}
    items = list(sheet.values)
    for i in range(len(items)):
        if i > 0:
            if items[i][0] not in survay:
                survay[items[i][0]] = {}

            if items[i][1] == 0:
                survay[items[i][0]]['text'] = items[i][2]
                survay[items[i][0]]['page'] = items[i][4]
            else:
                survay[items[i][0]][items[i][1]] = {
                    'text' : items[i][2],
                    'type' : SurvayConstants.get_type_index(items[i][3])
                }

    sheet    = wb['cluster']
    clusters = []
    items    = list(sheet.values)
    for i in range(len(items)):
        if i > 0:
            clusters.append({'number' : items[i][0], 'text' : items[i][1]})

    return survay, clusters

def __regist_servay(title, path, items, clusters):
    survay  = Survay(title=title, path=path)
    version = Version()
    survay.save()
    version.save()
    for category_number in items:
        category = Category(
            number=int(category_number),
            text=items[category_number]['text'],
            page=items[category_number]['page']
        )
        category.save()
        del items[category_number]['text']
        del items[category_number]['page']
        for question_number in items[category_number]:
            question = Question(
                number=int(question_number),
                text=items[category_number][question_number]['text'],
                type=items[category_number][question_number]['type']
            )
            question.save()
            category.questions.add(question)
        category.save()
        version.categories.add(category)
    version.save()
    survay.versions.add(version)

    for value in clusters:
        cluster = Cluster(**value)
        cluster.save()
        survay.clusters.add(cluster)

    survay.save()

sm_survay/templates/survay/create.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}アンケート新規登録{% endblock %}

{% block css %}
{% endblock %}

{% block script %}
<script>
  $('input[id=survay_file]').change(function() {
    var fileName = $(this).val();
    fileName = fileName.split('\\');
    fileName = fileName.length > 0 ? fileName[fileName.length - 1] : '';

    var ext = fileName.split('.');
    ext = ext.length > 0 ? ext[ext.length - 1] : '';

    if (ext === 'xlsx' || ext === 'xls') {
      $('#file_title').val(fileName);
    } else {
      alert('xlsxまたはxlsファイルのみ選択できます。');
      $(this).val(null);
      $('#file_title').val('');
    }
  });
</script>
{% endblock %}

{% block content %}
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Regist Survay <small>アンケート新規登録</small></h3>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">

      <form class="form-horizontal form-label-left" action="{% url 'survay:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="x_panel">
          <div class="x_title">
            <h2>アンケート情報</h2><div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br/>
            <div class="form-group">
              <label for="title" class="control-label col-md-3 col-sm-3 col-xs-12">
                タイトル<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="title" name="title" required="required" class="form-control col-md-7 col-xs-12" placeholder="最大100文字"/>
              </div>
            </div>

            <input id="survay_file" type="file" style="display:none" name="survay_file">
            <div class="form-group">
              <label for="file_title" class="control-label col-md-3 col-sm-3 col-xs-12">
                質問紙ファイル<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="input-group">
                  <input type="text" id="file_title" class="form-control" placeholder="xlsx or xlsファイルのみアップロード可" disabled>
                  <span class="input-group-btn">
                    <button type="button" class="btn btn-primary" onclick="$('input[id=survay_file]').click();">Browse</button>
                  </span>
                </div>
              </div>
            </div>

            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <a href="{% url 'survay:index' %}"><button class="btn btn-default" type="button">Cancel</button></a>
                <button type="submit" class="btn btn-success">Upload</button>
              </div>
            </div>
          </div>
        </div>
      </form>

    </div>
  </div>

</div>
{% endblock %}

sm_survay/templates/survay/detail.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load survay_tag %}

{% block title %}アンケート詳細{% endblock %}

{% block css %}
{% endblock %}

{% block script %}
<script>
$(function(){
  $('.editCluster').on('click', function(){
    $(this).closest('tr').find('td').each(function(index, ele){
      switch (index) {
        case 0:
          $('#number').val(ele.textContent);
          break;
        case 1:
          $('#text').val(ele.textContent);
          break;
        default:
          break;
      }
    });
  });
  $('#clusterSubmit').on('click', function(){
    var number = $('#number').val();
    var text = $('#text').val();
    var comment = $('#comment').val();
    var survayId = $('#survayId').val();
    if (number.length > 0 && text.length > 0 && comment.length > 0) {
      $.ajax({
        url: "{% url 'survay:edit' survay.id %}",
        type: 'post',
        data: {
          number: number,
          text: text,
          comment: comment
        },
        beforeSend: function(xhr, settings) {
           xhr.setRequestHeader("X-CSRFToken", $("input[name='csrfmiddlewaretoken']").val());
        }
      }).done(function(data){
        if (data.result == 'ok') {
          $('#modelCloseBtn').click();
          new PNotify({
            title: 'Success',
            text: '変更申請を行いました。',
            type: 'success',
            styling: 'bootstrap3'
          });
        }
      });
    } else {
      alert('全ての項目は必須です。');
    }
  });
});
</script>
{% endblock %}

{% block content %}
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Survay Detail <small>アンケート詳細</small></h3>
    </div>
    <div class="title_right">
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="col-md-12 text-right" style="margin:9px;">
    <a href="javascript:void(0);" onclick="var ok=confirm('本当に削除しますか？');if (ok) location.href='{% url 'survay:delete' survay.id %}'; return false;"><button class="btn btn-danger">削除</button></a>
  </div>

  <div class="x_panel col-md-12 col-sm-12 col-xs-12" style="margin-bottom:30px;">
    <div class="col-md-3 col-sm-3 col-xs-12 tile_stats_count">
      <span class="count_top">アンケート名：</span>
      <div class="count"><h2><strong>{{ survay.title }}</strong></h2></div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-12 tile_stats_count">
      <span class="count_top">最新バージョン：</span>
      <div class="count"><h2><strong>{% get_newest_version survay %}</strong></h2></div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-12 tile_stats_count">
      <span class="count_top">質問数：</span>
      <div class="count"><h2><strong>{% get_question_count survay %}</strong></h2></div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-12 tile_stats_count">
      <span class="count_top">登録日：</span>
      <div class="count"><h2><strong>{{ survay.updated_at }}</strong></h2></div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-12 tile_stats_count">
      <span class="count_top">最終更新日：</span>
      <div class="count"><h2><strong>{{ survay.updated_at }}</strong></h2></div>
    </div>
  </div>

  <div class="x_panel" style="margin-bottom:30px;">
    <div class="x_title" style="border-bottom:none;">
      <h2><strong>分類項目</strong></h2>
    </div>
    <div class="x_content">
      <table class="table table-hover">
        <tbody>
          {% get_clusters survay as clusters %}
          {% for cluster in clusters %}
          <tr>
            <td class="col-md-1 col-sm-1 col-xs-1">{{ cluster.number }}</td>
            <td>{{ cluster.text }}</td>
            <td class="col-md-1 col-sm-1 col-xs-1 text-center">
              <a class="editCluster" data-toggle="modal" data-target="#clusterModal"><i class="fa fa-edit fa-lg"></i></a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <div class="modal fade"id="clusterModal" tabindex="-1" role="dialog" aria-labelledby="clusterModal" aria-hidden="true">
    <div class="modal-dialog" style="width:800px;">
      <form class="form-horizontal form-label-left">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title"id="myModalLabel">文章編集</h4>
          </div>
          <div class="modal-body">
            <div class="form-group">
              {% csrf_token %}
              <input type="hidden" id="survayId" value="{{ survay.id }}"/>
              <label for="text" class="control-label col-md-3 col-sm-3 col-xs-12">番号<span class="required">*</span></label>
              <div class="col-md-7 col-sm-7 col-xs-12">
                <input type="text" id="number" name="number" class="form-control col-md-7 col-xs-12" disabled="disabled"/>
              </div>
            </div>
            <div class="form-group">
              <label for="text" class="control-label col-md-3 col-sm-3 col-xs-12">文章<span class="required">*</span></label>
              <div class="col-md-7 col-sm-7 col-xs-12">
                <textarea id="text" name="text" class="form-control col-md-7 col-xs-12" placeholder="最大500文字" rows="5"></textarea>
              </div>
            </div>
            <div class="form-group">
              <label for="comment" class="control-label col-md-3 col-sm-3 col-xs-12">変更点<span class="required">*</span></label>
              <div class="col-md-7 col-sm-7 col-xs-12">
                <textarea id="comment" name="comment" class="form-control col-md-7 col-xs-12" placeholder="最大500文字" rows="3"></textarea>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" id="modelCloseBtn">閉じる</button>
            <button type="button" class="btn btn-primary" id="clusterSubmit">変更を申請する</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  {% get_categories survay as categories %}
  {% for category in categories %}
  <div class="x_panel">
    <div class="x_title" style="border-bottom:none;">
      <h2><small>No. </small><strong>{{ category.number }}&nbsp;&nbsp;「{{ category.text }}」</strong></h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <table class="table table-hover">
        <tbody>
          {% get_questions category as questions %}
          {% for question in questions %}
          <tr>
            <td class="col-md-1 col-sm-1 col-xs-1">{{ question.number }}</td>
            <td>{{ question.text }}</td>
            <td  class="col-md-2 col-sm-2 col-xs-2">{% get_question_type question %}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="ln_solid"></div>
      <small class="pull-right">Page:{{ category.page }}</small>
    </div>
  </div>
  {% endfor %}<br/><br/><br/><br/><br/>

</div>
{% endblock %}

sm_survay/templates/survay/edit.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}アンケート編集{% endblock %}

{% block css %}
{% endblock %}

{% block script %}
<script>
  $('input[id=survay_file]').change(function() {
    var fileName = $(this).val();
    fileName = fileName.split('\\');
    fileName = fileName.length > 0 ? fileName[fileName.length - 1] : '';

    var ext = fileName.split('.');
    ext = ext.length > 0 ? ext[ext.length - 1] : '';

    if (ext === 'xlsx' || ext === 'xls') {
      $('#file_title').val(fileName);
    } else {
      alert('xlsxまたはxlsファイルのみ選択できます。');
      $(this).val(null);
      $('#file_title').val('');
    }
  });
</script>
{% endblock %}

{% block content %}
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Regist Survay <small>アンケート編集</small></h3>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">

      <form class="form-horizontal form-label-left" action="{% url 'survay:edit' survay.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="x_panel">
          <div class="x_title">
            <h2>アンケート情報</h2><div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br/>
            <div class="col-md-12 text-center">
              <p>アンケートのテンプレートファイルは&nbsp;<strong><a href="{% url 'survay:download' survay.id %}" style="color:red;"><u>コチラ</u></a></strong>&nbsp;からダウンロードしてください。</p>
            </div>
            <div class="form-group">
              <label for="title" class="control-label col-md-3 col-sm-3 col-xs-12">
                タイトル<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="title" name="title" required="required" class="form-control col-md-7 col-xs-12" placeholder="最大100文字" value="{{ survay.title }}"/>
              </div>
            </div>

            <input id="survay_file" type="file" style="display:none" name="survay_file">
            <div class="form-group">
              <label for="file_title" class="control-label col-md-3 col-sm-3 col-xs-12">更新用ファイル</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="input-group">
                  <input type="text" id="file_title" class="form-control" placeholder="xlsx or xlsファイルのみアップロード可" disabled>
                  <span class="input-group-btn">
                    <button type="button" class="btn btn-primary" onclick="$('input[id=survay_file]').click();">Browse</button>
                  </span>
                </div>
              </div>
            </div>

            <div class="form-group">
              <label for="comment" class="control-label col-md-3 col-sm-3 col-xs-12">変更点</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <textarea id="comment" name="comment" class="form-control col-md-7 col-xs-12" placeholder="最大500文字" rows="3"></textarea>
              </div>
            </div>

            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <a href="{% url 'survay:index' %}"><button class="btn btn-default" type="button">Cancel</button></a>
                <button type="submit" class="btn btn-success">Submit</button>
              </div>
            </div>
          </div>
        </div>
      </form>

    </div>
  </div>

</div>
{% endblock %}

sm_survay/templates/survay/index.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load survay_tag %}

{% block title %}アンケート一覧{% endblock %}

{% block css %}
{% endblock %}

{% block script %}
{% endblock %}

{% block content %}
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Survay List <small>アンケート一覧</small></h3>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <a href="{% url 'survay:create' %}"><button class="btn btn-primary">新規作成</button></a>
        </div>
        <div class="x_content">
          <div class="table-responsive">
            <table class="table table-striped jambo_table bulk_action">
              <thead>
                <tr class="heading">
                  <td class="column-title">No.</td>
                  <td class="column-title">タイトル</td>
                  <td class="column-title">最新バージョン</td>
                  <td class="column-title">質問数</td>
                  <td class="column-title">登録日</td>
                  <td class="column-title">最終更新日</td>
                  <td class="column-title text-center">操作</td>
                </tr>
              </thead>
              <tbody>
                {% if survays %}
                  {% for item in survays %}
                    <tr>
                      <td>{{ forloop.counter }}</td>
                      <td>
                          <a href="{% url 'survay:detail' item.id %}">
                            {{ item.title }}
                          </a>
                      </td>
                      <td>{% get_newest_version item %}</td>
                      <td>{% get_question_count item %}</td>
                      <td>{{ item.created_at }}</td>
                      <td>{{ item.updated_at }}</td>
                      <td class="text-center">
                        <a href="{% url 'survay:edit' item.id %}"><i class="fa fa-edit fa-lg"></i></a>&nbsp;&nbsp;
                        <a href="javascript:void(0);" onclick="var ok=confirm('本当に削除しますか？');if (ok) location.href='{% url 'survay:delete' item.id %}'; return false;"><i class="fa fa-trash fa-lg"></i></a>
                      </td>
                    </tr>
                  {% endfor %}
                {% else %}
                <tr>
                  <td colspan="7">
                    <div class="alert alert-danger fade in" role="alert">
                      <strong>現在、登録されているアンケートはありません。</strong>
                    </div>
                  </td>
                </tr>
                {% endif %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock %}