authuser/urls.py
from django.urls import path
from . import views

app_name = 'authuser'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

sm_dashboard/urls.py
from django.conf.urls import url
from . import views

app_name = 'dashboard'

urlpatterns = [
    url(r'^index/', views.index_template, name='index'),
]

sm_data/urls.py
from django.urls import path
from . import views

app_name = 'data'

urlpatterns = [
    path('regist/', views.regist_data, name='regist'),
]

sm_survay/urls.py
from django.urls import path
from . import views

app_name = 'survay'

urlpatterns = [
    path('index/', views.index_template, name='index'),
    path('create/', views.create_template, name='create'),
    path('history/', views.history_template, name='history'),
    path('detail/<int:pk>', views.detail_template, name='detail'),
    path('edit/<int:pk>', views.edit_template, name='edit'),
    path('delete/<int:pk>', views.delete_survay, name='delete'),
    path('delete/cluster_log/<int:pk>', views.delete_cluster_log, name='delete_cluster_log'),
    path('download/<int:pk>', views.download, name='download'),
]

survay_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('auth/', include('authuser.urls')),
    path('api/data/', include('sm_data.urls')),
    path('mng/dashboard/', include('sm_dashboard.urls')),
    path('mng/survay/', include('sm_survay.urls')),
]

sm_dashboard/models.py
from django.db import models

# Create your models here.

sm_dashboard/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required

@login_required
def index_template(request):
    return render(request, 'dashboard/index.html')

sm_dashboard/templates/layouts/alert.html
{% load layout_tag %}
{% show_alert request as alert %}

{% if alert.is_show %}
<div class="col-md-12">
  <div class="alert alert-{{ alert.type }} alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    {{ alert.text }}
  </div>
</div>
{% endif %}

sm_dashboard/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" href="images/favicon.ico" type="image/ico" />

    <title>アンケート管理システム | {% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static "vendors/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static "vendors/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static "vendors/nprogress/nprogress.css" %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static "vendors/iCheck/skins/flat/green.css" %}" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="{% static "vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" %}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{% static "vendors/jqvmap/dist/jqvmap.min.css" %}" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="{% static "vendors/bootstrap-daterangepicker/daterangepicker.css" %}" rel="stylesheet">
    <!-- PNotify -->
    <link href="{% static "vendors/pnotify/dist/pnotify.css" %}" rel="stylesheet">
    <link href="{% static "vendors/pnotify/dist/pnotify.buttons.css" %}" rel="stylesheet">
    <link href="{% static "vendors/pnotify/dist/pnotify.nonblock.css" %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static "css/custom.min.css" %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
  </head>

  <body class="nav-md footer_fixed">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col menu_fixed">
          <div class="left_col scroll-view">
            {% include 'layouts/sidebar.html' %}
          </div>
        </div>

        {% include 'layouts/header.html' %}

        <div class="right_col" role="main">
          {% include 'layouts/alert.html' %}

          {% block content %}
          {% endblock %}
        </div>
        <!-- /page content -->

        <!-- footer content -->
        {% include 'layouts/footer.html' %}
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static "vendors/jquery/dist/jquery.min.js" %}"></script>
    <!-- Bootstrap -->
    <script src="{% static "vendors/bootstrap/dist/js/bootstrap.min.js" %}"></script>
    <!-- FastClick -->
    <script src="{% static "vendors/fastclick/lib/fastclick.js" %}"></script>
    <!-- NProgress -->
    <script src="{% static "vendors/nprogress/nprogress.js" %}"></script>
    <!-- Chart.js -->
    <script src="{% static "vendors/Chart.js/dist/Chart.min.js" %}"></script>
    <!-- gauge.js -->
    <script src="{% static "vendors/gauge.js/dist/gauge.min.js" %}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{% static "vendors/bootstrap-progressbar/bootstrap-progressbar.min.js" %}"></script>
    <!-- iCheck -->
    <script src="{% static "vendors/iCheck/icheck.min.js" %}"></script>
    <!-- Skycons -->
    <script src="{% static "vendors/skycons/skycons.js" %}"></script>
    <!-- Flot -->
    <script src="{% static "vendors/Flot/jquery.flot.js" %}"></script>
    <script src="{% static "vendors/Flot/jquery.flot.pie.js" %}"></script>
    <script src="{% static "vendors/Flot/jquery.flot.time.js" %}"></script>
    <script src="{% static "vendors/Flot/jquery.flot.stack.js" %}"></script>
    <script src="{% static "vendors/Flot/jquery.flot.resize.js" %}"></script>
    <!-- Flot plugins -->
    <script src="{% static "vendors/flot.orderbars/js/jquery.flot.orderBars.js" %}"></script>
    <script src="{% static "vendors/flot-spline/js/jquery.flot.spline.min.js" %}"></script>
    <script src="{% static "vendors/flot.curvedlines/curvedLines.js" %}"></script>
    <!-- DateJS -->
    <script src="{% static "vendors/DateJS/build/date.js" %}"></script>
    <!-- JQVMap -->
    <script src="{% static "vendors/jqvmap/dist/jquery.vmap.js" %}"></script>
    <script src="{% static "vendors/jqvmap/dist/maps/jquery.vmap.world.js" %}"></script>
    <script src="{% static "vendors/jqvmap/examples/js/jquery.vmap.sampledata.js" %}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{% static "vendors/moment/min/moment.min.js" %}"></script>
    <script src="{% static "vendors/bootstrap-daterangepicker/daterangepicker.js" %}"></script>
    <!-- PNotify -->
    <script src="{% static "vendors/pnotify/dist/pnotify.js" %}"></script>
    <script src="{% static "vendors/pnotify/dist/pnotify.buttons.js" %}"></script>
    <script src="{% static "vendors/pnotify/dist/pnotify.nonblock.js" %}"></script>
    <!-- Custom Theme Scripts -->
    <script src="{% static "js/custom.min.js" %}"></script>
    <script>
    $(document).ready(function (){
      $('.ui-pnotify').remove();
    });
    </script>

    {% block script %}
    {% endblock %}
  </body>
</html>

sm_dashboard/templates/layouts/footer.html
<footer>
  <div class="pull-right">
    Survay Management System by <a href="https://fotome.jp">Fotome.Inc</a>
  </div>
  <div class="clearfix"></div>
</footer>

sm_dashboard/templates/layouts/header.html
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="{% url 'authuser:logout' %}">
            <button class="btn btn-primary">Log Out&nbsp;&nbsp;<i class="fa fa-sign-out"></i></button>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</div>

sm_dashboard/templates/layouts/sidebar.html
{% load static %}
<div class="navbar nav_title" style="border: 0;">
  <a href="{% url 'dashboard:index' %}" class="site_title"><i class="fa fa-cube"></i> <span>Survay Manager</span></a>
</div>
<div class="clearfix"></div>

<div class="profile clearfix">
  <div class="profile_pic">
    <img src="{% static "images/img.jpg" %}" alt="..." class="img-circle profile_img">
  </div>
  <div class="profile_info">
    <span>Welcome,</span>
    <h2>{{ user.username }} <small>さん</small></h2>
  </div>
</div>
<br />

<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <h3>Menu</h3>
    <ul class="nav side-menu">
      <li><a href="{% url 'dashboard:index' %}"><i class="fa fa-dashboard"></i> ダッシュボード</a></li>
      <li><a><i class="fa fa-file-text"></i> アンケート管理<span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="{% url 'survay:index' %}">アンケート一覧</a></li>
          <li><a href="{% url 'survay:history' %}">更新履歴</a></li>
          <li><a href="index2.html">集計結果一覧</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

<div class="sidebar-footer hidden-small">
  <a data-toggle="tooltip" data-placement="top" title="Settings">
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
  </a>
</div>